### ISSUE TITLE
Segfault on Windows when redirecting `STDOUT/STDERR` to the same stream

### ISSUE THREAD

**Issue by tylanphear** [StanzaOrg/lbstanza-old#103]
For example, if you compile the following test program:

```stanza
defpackage test:
  import core

defn main ():
  val args = command-line-arguments()
  Process(args[1], args[1 through false], STANDARD-IN, PROCESS-OUT, PROCESS-OUT)

main()
```

And run it, passing any valid executable as an argument (e.g. `./test gcc`), the test program seems to run fine in most cases. However, sometimes it will cause a segmentation violation. If run in the debugger (I used `gdb`), this segfault occurs reliably. This is due to an exception being thrown in the Windows runtime due to our closing a file handle twice.

Specifically, we redirect `STDOUT` and `STDERR` to the same handle (the `PROCESS-OUT` pipe), spawn the process with its `STDOUT` and `STDERR` set to the write end of the pipe, and then close those write ends in our process. However, since `STDOUT` and `STDERR` point to the same pipe, the latter action closes the `PROCESS-OUT` pipe twice, causing a segfault.

The same behavior can be observed if both streams are redirected to `PROCESS-ERR` (other combinations of redirections are not yet supported.)

**Comment by CuppoJava** [comment]
Good find. Definitely a bug.

**Comment by OlegPliss** [comment]
You should not pass `PROCESS-OUT` handle twice without duplicating it.

There are objects (files, streams...) and handles. Multiple handles can refer to the same object. Each handle can only be closed once. If you need another reference to the same object, duplicate the handle.

**Comment by tylanphear** [comment]
> You should not pass `PROCESS-OUT` handle twice without duplicating it.
> 
> There are objects (files, streams...) and handles. Multiple handles can refer to the same object. Each handle can only be closed once. If you need another reference to the same object, duplicate the handle.

To be clear `PROCESS-OUT` is not actually a handle. It is an integer referring to a stream specifier which is then passed to the Stanza runtime `stz_int launch_process(...)` that creates a pipe and passes the appropriate end to the child process. Nevertheless, I believe your point stands with regards to the pipe handle we pass.

If I understand it correctly, we should open a pipe (for a PROCESS redirection), and then duplicate the appropriate end to pass to the child process, however many times we need to?

**Comment by OlegPliss** [comment]
I mean, it is not specific to Windows. It is illegal to close the same handle twice under Linux too regardless of segfaults. OS already implements reference counting for objects via handles, why to invent out own mechanism?

**Comment by tylanphear** [comment]
> I mean, it is not specific to Windows. It is illegal to close the same handle twice under Linux too regardless of segfaults. OS already implements reference counting for objects via handles, why to invent out own mechanism?

I'm not sure as to what you are referring to. The issue I am describing is not a factor on Linux.

I shouldn't really speak to the Linux implementation in specific detail, but the process model there, as well as the implementation of the runtime, is much different than on Windows. On Linux, when a new process is launched, the launcher daemon spawned by the runtime `fork()`s and then, in the child process, we:
  * Open a named pipe for each standard input/output/error stream
  * Set it as the corresponding standard stream descriptor
  * `exec()` the program

We use an entirely different mechanism on Windows because the process model doesn't use `fork/exec()` (as I'm sure you know.)

Instead, on Windows, when a new process is launched, we:
 *  Create a pipe for each redirected stream
 *  Pass the corresponding read/write end to `CreateProcess()` as one of its standard file handles
 *  Close the ends that I passed to to the child process.

Don't we need to perform that last step, or am I reading the Windows docs incorrectly?
