### ISSUE TITLE
Failed to compile examples in CentOS 7

### ISSUE THREAD

**Issue by dram** [StanzaOrg/lbstanza-old#11]
When trying to compile helloworld example in CentOS 7, stanza failed silently with only one word message:

```
% stanza examples/helloworld.stanza -o helloworld
Killed
```

Other programs in `examples/` are all the same.

Do not know how to diagnose this problem, any hint?

**Comment by CuppoJava** [comment]
Thanks for the bug report. Can you please verify that 
   1) You're using the 64-bit version of CentOS.
   2) You installed stanza using "stanza install -platform linux" ?

If so, then it seems there's something different about CentOS compared to Ubuntu that we're not expecting. We'll install a CentOS distribution ourselves and fix it.

**Comment by dram** [comment]
Yes, I'm using 64-bit version, and stanza is installed with `-platform linux`.

Btw, `stanza version` runs successfully.

**Comment by CuppoJava** [comment]
Okay. Thanks for checking. In that case, this looks like our problem. 

Thanks for the bug report!

**Comment by dram** [comment]
My previous system's memory is a bit low and swap is not enabled, `stanza` may be killed by kernel because of memory exhaustion.

Now I try on another VM which have more memory (3G) and with swap enabled, `stanza` failed with following message:

```
% stanza examples/helloworld.stanza -o helloworld
cc -std=c99 'tmp1.s' '/home/dram/stanza/mystanza/runtime/driver.c' -o 'helloworld' -lm
Cannot allocate memory
```

Is 3G memory enough to run Stanza?

**Comment by dram** [comment]
My fault.

That VM's memory was consumed by some other processes, after stop them, `stanza` compiles `helloworld` successfully.

Btw, it seems that Stanza's memory usage is quite a bit high. as I observed in `top`, it takes approximately 1G to compile `helloworld` example.

**Comment by CuppoJava** [comment]
The memory usage is a mistake. We were experimenting with larger heap sizes for the purposes of speeding up the bootstrapping process but forgot to turn it back down for release. I'll rebuild a new version that uses a much more reasonable amount of memory.
  -Patrick
