### ISSUE TITLE
Mis-indented code compiled succesfully without error

### ISSUE THREAD

**Issue by dram** [StanzaOrg/lbstanza-old#14]
No error is reported when compiling following code with Stanza 0.9.1, which is supposed to be an error as [stated](http://lbstanza.org/chapter2.html#anchor149) in Stanza by Example. 

```
defpackage mypackage :
  import core

defn main () :
println("Code goes here")

main()
```

**Comment by CuppoJava** [comment]
That's a mistake in Stanza by Example. It should read. We'll fix the website.

```
defpackage mypackage :
import core

defn main () :
  println("Code goes here")

main()
```

**Comment by CuppoJava** [comment]
Fixed.
