### ISSUE TITLE
command-line-arguments() has different behavior when using `stanza run`

### ISSUE THREAD

**Issue by tylanphear** [StanzaOrg/lbstanza-old#145]
When you pass arguments to `stanza run` the behavior of `command-line-arguments()` is inconsistent with the behavior of `command-line-arguments()` when the same action is performed with the compiled version:

```
$ echo "println(command-line-arguments())" > test.stanza
$ stanza test.stanza -o test
$ ./test foo bar
["./test" "foo" "bar"]
$ stanza run test.stanza -- foo bar
["foo" "bar"]
```

the issue is [compiler/stz-main.stanza](https://github.com/StanzaOrg/lbstanza/blob/784ff8e8edf89027ac68f58e31796b661bfe560f/compiler/stz-main.stanza#L540) (by the way, this isn't the same code as in the [PR](#143) that was supposed to have introduced it, which is *very* confusing). It should be setting up the `command-line-arguments()` with the program's name, and *then* the program args, so the above should result in

```
$ ./test foo bar
["./test" "foo" "bar"]
$ stanza run test.stanza -- foo bar
["test.stanza" "foo" "bar"]
```

**Comment by CuppoJava** [comment]
Thanks. This is now fixed.
