### ISSUE TITLE
Multi-dimensional arrays?

### ISSUE THREAD

**Issue by bardo84** [StanzaOrg/lbstanza-old#146]
(copy from https://www.reddit.com/r/lbstanza/comments/s58kob/multidimensional_vectors)

Hi,
I saw vector of vectors mentioned, but are not sure how to dimension or call them.
How would you implement linear algebra operations like matrix/vector, matrix/matrix multiplication or a linear system solver?
Thx

**Comment by CuppoJava** [comment]
Hello!

You have two potential designs for a multi-dimensional vector. 

1) You can either directly create a vector of vectors. Here's an example:
```
val v = Vector<Vector<Float>>()
add(v, Vector<Float>())
add(v, Vector<Float>())
add(v[0], 1.1f)
add(v[0], 2.2f)
add(v[1], 3.3f)
add(v[1], 4.4f)
```

To access the element in the second two, first column, you can use
```
val x = v[1][0]
```

2) You can create a type and overload the `get` and `set` multis.

```
deftype MyMatrix
defmulti get (m:MyMatrix, row:Int, col:Int) -> Float
defmulti set (m:MyMatrix, row:Int, col:Int, v:Float) -> False

defn MyMatrix () :
  ... my implementation of MyMatrix ...
```

This will allow you to use your matrix like this:

```
val m = MyMatrix()
m[0, 0] = 1.1f
m[0, 1] = 2.2f
m[1, 0] = 3.3f
m[1, 1] = 4.4f
```

You can implement `MyMatrix` however you like. You can use a Vector of Vectors internally, or an Array of Arrays, or a single Array that has the items listed row-by-row. 

Once you have matrices implemented, the rest of the linear algebra operations can be implemented in the usual way.

Patrick
