### ISSUE TITLE
No link to homepage inside Stanza by Example

### ISSUE THREAD

**Issue by dram** [StanzaOrg/lbstanza-old#16]
There is no link to go back to homepage inside [Stanza by Example](http://lbstanza.org/stanzabyexample.html) pages.

I think logo icon on the top left is a good place to have a such link.

**Comment by CuppoJava** [comment]
Good idea.

**Comment by CuppoJava** [comment]
Added a home link to the Stanza by Example pages. Later on, we'll fold that link nicely into the logo icon, but this will do for now.
