### ISSUE TITLE
Homebrew/Linuxbrew Tap

### ISSUE THREAD

**Issue by MadcapJake** [StanzaOrg/lbstanza-old#17]
I've created a [Homebrew](http://brew.sh)/[Linuxbrew](http://linuxbrew.sh) [Tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) for installing stanza [here](https://github.com/MadcapJake/homebrew-lbstanza).  With this you can install stanza very easily.

``` sh
brew install MadcapJake/lbstanza/stanza-linux  # or stanza-mac
```

I was wondering if you want to move that repo to the StanzaOrg, it might look nice (would change that tap to `StanzaOrg/tap/stanza-linux`) but not necessary.  Perhaps you'd also add it to the Downloads page as an installation option?

**Comment by CuppoJava** [comment]
Awesome! Thanks. 
I'll add that to the Downloads page, along with the link to the IRC channel you created.

**Comment by CuppoJava** [comment]
Added link to the Download page. Let's temporarily keep the repo where it is for now, until I get some other things sorted out. Thanks again!

**Comment by haze** [comment]
This does not work, [pic](http://oops.moe/Z7VSF.png)

**Comment by MadcapJake** [comment]
Perhaps you could open an issue in the [tap](https://github.com/MadcapJake/homebrew-lbstanza)? But I'm wondering if it might be because you need to type `MadcapJake` and not `madcapjake` (though it works on linux no matter the casing).  Another option would be to try:

```
brew tap MadcapJake/lbstanza
brew install stanza-mac
```
