### ISSUE TITLE
stz, a stanza Fish Shell function

### ISSUE THREAD

**Issue by MadcapJake** [StanzaOrg/lbstanza-old#18]
I've also created a wrapper called [`stz`](https://github.com/fisherman/stz), for Fish Shell, that gives you a quick way to execute one-liners and scripts.

``` sh
brew install fisherman/tap/fisherman # works easily with fisherman plugin manager
fisher i stz
set -Ux STX_BIN "/path/to/stanza" # not needed with linuxbrew or /usr/local/bin loc
stz -e 'print(1)' # converts to a temp script file, compiles that, and executes it.
stz -r some-stanza-file.stanza # compiles the provided file and executes it
stz compile some-stanza-file.stanza -o some-stanza-bin # passes anything else to stanza
```

Just thought I'd share since I'm not aware of a mailing list or forum and no one comes on IRC yet :smile:

**Comment by CuppoJava** [comment]
Cool. I was a big Scheme programmer, and this is a great utility until we get a general REPL up.

We've created a groups.io mailing list. I'll post it on the website soon. The IRC channel will pick up once the link is on the official webpage. (I'm getting to it I promise.)

**Comment by MadcapJake** [comment]
Awesome, I crafted a post on groups.io, though no one knows it's there, perhaps it can kickstart some conversation when people arrive!

This coupled with the homebrew formulae really improve the interest-to-playing-with-the-langauge time (for those using Fish shell at least) and I think that's an important thing to try and reduce when you're looking to build a community.

**Comment by CuppoJava** [comment]
That's great. I'll post the link soon.

Reducing the barriers to entry is indeed really important. Google analytics gives me a sense of how many minutes I have to impress someone with Stanza. After 5 minutes, it's an exponential drop-off.

**Comment by CuppoJava** [comment]
The mailing list has been made publicly accessible on the webpage. Thanks for writing the first post!

**Comment by haze** [comment]
Try using [this](https://github.com/hvze/sbt), it's my own build tool.

**Comment by CuppoJava** [comment]
Cool. And it's written in Stanza too! Post it on the mailing list!
