### ISSUE TITLE
Add "stanza check" compiler command

### ISSUE THREAD

**Issue by MadcapJake** [StanzaOrg/lbstanza-old#25]
I think Stanza's analysis prior to compiling would be really nice to integrate into editors but it would be best to ensure the process closes post-analysis instead of continuing through the compilation process.  You could provide a `-c` flag to the `compile` subcommand (to be used instead of `-o` or `-s`) or maybe an entire subcommand `check`.

Otherwise, both `-o` and `-s` take between 10-20 seconds on my machine to complete.

As an aside, using [atom-build](https://github.com/noseglid/atom-build) with this `.atom-build.json` file (in your project's base directory) does quite well and even highlights any errors in the file (though it would need some tweaking to include any other needed stanza files for larger projects):

``` json
{
  "cmd": "stanza",
  "args": ["compile", "{FILE_ACTIVE}", "-o", "{FILE_ACTIVE_NAME_BASE}"],
  "cwd": "{PROJECT_PATH}",
  "sh": true,
  "name": "L.B. Stanza Compile",
  "errorMatch": [
    "(?<file>[\\w\\/\\.\\-]+):(?<line>\\d+)\\.(?<col>\\d+):(?<message>.+)(?: Possibilities are:)?"
  ]
}
```

**Comment by CuppoJava** [comment]
That's a good idea. I will add a "stanza check" command to the compiler that only runs the syntax and type checker. That part actually does run decently well (e.g. less than a second for ~1000Loc projects).

Is there any particular formatting convention that I should use for the error messages to make your life easier?

**Comment by MadcapJake** [comment]
Currently I think they are well-formatted (they seem to follow [GNU standards](https://www.gnu.org/prep/standards/html_node/Errors.html)).  The key is to stay as regular as possible.

**Comment by MadcapJake** [comment]
Any chance this could see progress soon? I have some free time this week to integrate it into Atom and Howl.

**Comment by CuppoJava** [comment]
Hi Jake. Version 0.10.0 took a little more time than I was planning, but I just got it done this morning. I'll release it tomorrow after I double-check some things. Thanks for waiting!

**Comment by MadcapJake** [comment]
Awesome! I really appreciate you adding this feature and thanks for all your hard work on Stanza, in general!

**Comment by CuppoJava** [comment]
No thank you! It's awesome to have you working on proper editor support for Stanza!
