### ISSUE TITLE
Add multi line comments

### ISSUE THREAD

**Issue by porky11** [StanzaOrg/lbstanza-old#28]
Multi line commetns are useful for uncommenting not working stuff

**Comment by sumit0190** [comment]
This seems pretty easy to accomplish (the usual "parse string till you find terminating syntax" approach comes to mind), but we must first decide what character(s) should we use to denote multi-line comments. We can go the CoffeeScript way (; for single-line comments, ;;; or ;; for multi-line comments), or maybe we can designate another character for it. 
@CuppoJava what do you think?

**Comment by MadcapJake** [comment]
Three other options:
- `;* ... *;`
- `;- ... -;`
- `;{ ... }`

**Comment by CuppoJava** [comment]
Sounds good. I'm partial to the

```
;{ ... };
```

syntax myself. It's easy to add a C-style `/* ... */` multi line quote, but I've never liked how it didn't nest properly. So I would like Stanza's multi-line comment to nest appropriately.

**Comment by porky11** [comment]
using `;{…}` for comments seems to be a bad Idea
one could want to uncomment an anonymous function, then it would be confusing:

```
val x = 1 ;{_ + 1}(1)
println(x)
```

Then it should be  `;;` (or more) instead of `;` for single line comments to avoid this

and why should there be a `;` after the last `}`?

**Comment by CuppoJava** [comment]
Good point. Well I don't have any particular opinion on the special characters to use. The only thing that I want is support for proper nesting behaviour. So I'll dwell on it a bit more.

**Comment by MadcapJake** [comment]
Perl 6 uses an additional special character (tilde) to signify that the following matched delimiters surround an [embedded comment](https://doc.perl6.org/language/syntax#Comments). I could see tilde being used in the same way in Stanza as it would match how s-expression literals are written.

``` perl6
# is a Perl 6 single line comment
#`(is an enclosed comment) my $i = 10
#`{any braces work} our $j = 20
```

**Comment by CuppoJava** [comment]
I read through the Perl 6 documentation, and wondered about what happens in the case of unmatched parenthesis in strings.

```
#`(is a "this ) is unmatched" comment) my $i = 10
```

This behaviour could be fairly subtle. Since it costs so little for us to design a mechanism that is more likely to always work, I'm leaning towards (possibly more verbose) but bullet-proof combination of characters.

Here's one that I'm considering. It has the advantage of basically being guaranteed to work, but the disadvantage of being verbose. What do you think?

```
;<MYTAG> Everything after this
defn myfunction (i) :
   for i in 0 to 10 do :
      do(myfunction{_, i}, xs)
and before this is a comment <MYTAG>
```

**Comment by sumit0190** [comment]
@CuppoJava I like that idea. The only problem that might arise is if you want to have un-escaped strings in your comments and they use the same tags as the comment, but then I don't really see why anyone would do that in the first place.

**Comment by porky11** [comment]
I don't like the idea
it seems like xml unneccessary complicated
and the problem with using single `;` for both kinds of comments still isn't solved this way

and if i have some random data in comment I don't want to have to check for single `"` in them

comment endings and beginnings should be some short strings noone would use in code normally
(why not use `/*` `*/` like in c or `#|` `|#` like in common lisp?)

but maybe when strings contain start and end-signs from comments, it may be better, that strings will be seen as strings, for example when using c-style-comments
`/* val c-like-source-code = "/* this will be " */` the unfinished comment in source is bad

**Comment by MadcapJake** [comment]
But @porky11 that's how raw strings are done (the xml-like tag).

How is the problem of `;` not solved? If `;` is followed by `<some-tag>` then that indicates to the compiler that it is an embedded comment.

Why use a completely unrelated syntax from C or CL?

**Comment by CuppoJava** [comment]
Okay. Thanks for everyone's input. I'll go ahead with the `;<MYTAG> my comment <MYTAG>` syntax for the following reasons:
1. It is guaranteed to work. You can comment any chunk of code anywhere. If your `MYTAG` is being used already, then you can simply select a different one.
2. It allows for nested comments but without the headache of defining how balanced brackets are defined (e.g. whether brackets in string literals count towards it).
3. It has an elegant failure mode. If you accidentally try to comment out some legitimate code `<fgh>` and write `;<fgh>`, then you are likely to get an error from Stanza telling you that you started a block comment with the tag `fgh` but it couldn't find an ending tag.

**Comment by MadcapJake** [comment]
I like that having a tag name allows you to encode some meaning into each comment block:

```
;<NAME>Foo<NAME>

;<DESCRIPTION>
Provides an interface to the amazing libfoobar in Stanza
<DESCRIPTION>

;<SYNOPSIS>
defpackage baz :
    import foo

val quux = bar(12)
<SYNOPSIS>

;<CAVEATS>
Does not support strings
<CAVEATS>

;<LICENSE>MIT<LICENSE>
;<AUTHOR>Jake Russo<AUTHOR>

defpackage foo :
    import core

public defn bar (x:Int) :
    ;<FN>Returns the result of calling foobar_bar on an integer<FN>
    ...
```

Would be cool if there was some way to access them internally but could also be a separate tool that creates HTML docs built from them.

**Comment by CuppoJava** [comment]
That's a cool use case. I'm pretty excited about this feature then. I'll add the syntax addition now, and then later we'll see how best to expose this information to a tools dev.

**Comment by MadcapJake** [comment]
Was this added in the latest `0.10.x` updates?

**Comment by CuppoJava** [comment]
Not yet. It's coming soon.

**Comment by CuppoJava** [comment]
Supported in 0.10.2. Syntax is:

```
;<MYTAG> This is a comment <MYTAG>
```
