### ISSUE TITLE
Defstruct doesn't work with ?T

### ISSUE THREAD

**Issue by porky11** [StanzaOrg/lbstanza-old#29]
I want to be able to write

```
defstruct Complex<?T>:
  real : ?T
  imag : T

```

instead of

```
deftype Complex<T>

defmulti real<?T> (complex:Complex<?T>) -> T
defmulti imag<?T> (complex:Complex<?T>) -> T

defn Complex<?T> (real:?T imag:T):
  new Complex:
    defmethod real (this):
      real
    defmethod imag (this):
      imag
```

**Comment by CuppoJava** [comment]
That was something that we discussed and ultimately decided that the syntax is quite confusing. But there's a very easy (and, in my opinion, clearer) workaround. You just need to define your own constructor function that takes a captured type argument.

```
defstruct Complex<T> :
  real:T
  imag:T

defn Complex<?T> (real:?T, imag:?T) :
  Complex<T>(real, imag)
```

**Comment by porky11** [comment]
I didn't think, Complex<T> and Complex<?T> are different functions (that writing T is optional with ?) , and this seemed like a recursive call then
