### ISSUE TITLE
GADT

### ISSUE THREAD

**Issue by sirinath** [StanzaOrg/lbstanza-old#3]
Have [GADT](https://en.wikipedia.org/wiki/Generalized_algebraic_data_type) so Stanza syntax can be represented as [HOAS](https://en.wikipedia.org/wiki/Higher-order_abstract_syntax) for better Meta Programming capabilities.

**Comment by CuppoJava** [comment]
There is still some open theoretical questions about how GADTs interact with systems that support subtyping. We like GADTs too but until we (or someone else) solves these issues, they will left for later.

**Comment by sirinath** [comment]
I believe you can do this by tagging and annotations. See how: Nim-lang.org, x10-lang.org does this.
