### ISSUE TITLE
Function arguments cannot be captured

### ISSUE THREAD

**Issue by porky11** [StanzaOrg/lbstanza-old#31]
Why isn't this possible?

```
defn compose<?T ?U ?V> (f:?T -> ?U g:U -> ?V) -> T -> V :
  {g $ f $ _}
```

**Comment by CuppoJava** [comment]
Our theoretical framework currently does not support capturing from contravariant positions. We found that this rarely comes up in practice, but the `compose` function is indeed one place where it would be nice to have. Once we work out the theory, we'll add this feature, but for now you'll have to give the contravariant arguments explicitly.

```
defn compose<T,?U,?V> (f:T -> ?U, g:U -> ?V) -> (T -> V) :
   {g $ f $ _}
```
