### ISSUE TITLE
label without explicit type should return False

### ISSUE THREAD

**Issue by MadcapJake** [StanzaOrg/lbstanza-old#33]
When you have an untyped label, Stanza still expects you to return something:

```
label ret :
    ...
    ret()
```

Gives you `Cannot call function ret of type ? -> Void with arguments of type ().`

So you have to do:

```
label ret :
    ...
    ret(true)
```

Is this expected behavior?

**Comment by CuppoJava** [comment]
It would be useful to hear your opinion on this Jake. When a type is not given to a `label` construct, there were two interpretations that people naturally leapt to.

The first interpretation is that it's equivalent to `label<?>`. Thus

```
label ret : 
   ...
   ret(3)
```

is equivalent to

```
label<?> ret : 
   ...
   ret(3)
```

So under this interpretation, you still need to provide a value to return.

The second interpretation is that it's a `label` that doesn't return anything meaninful. Thus

```
label ret : 
   ...
   ret()
```

is equivalent to

```
label<False> ret : 
   ...
   ret(false)
```

We went with the first interpretation to be consistent with the `generate` expression. But perhaps the second interpretation is the more common interpretation.

**Comment by MadcapJake** [comment]
My intuition is that `label<?>` would mean "return something" and `label` would mean "return nothing". I would argue that `generate` deals explicitly with creation of sequences so expecting no parameter to mean `<?>` is intuitive. However, `label` is a much more general structure so expecting no parameter to mean `<?>` seems less intuitive (to me).

What is the type of `()`? At least having _some_ way of saying "return nothing" would be beneficial.

**Comment by CuppoJava** [comment]
Okay. I think that's sensible. I just scoured through my own sources and found that if I actually had something to return, I tended used `label<T>` 100% of the time. We will change `label` to behave like `while` and simply return `false`, and the exit function will no longer take any arguments.

**Comment by CuppoJava** [comment]
Supported in 0.10.2.
