### ISSUE TITLE
Compile time errors for 'x' == "x"?

### ISSUE THREAD

**Issue by dwnusbaum** [StanzaOrg/lbstanza-old#34]
I recently wrote something like the following:

```
val char:Char = foo(bar)
if char == 'x' or char =="y":
    println("branch 1")
else:
    println("branch 2")
```

And couldn't figure out why branch 1 was not executing when `char` was `'y'`. The issue is that `y` is in double quotes in the comparison, making it a `String` rather than a `Char`, so the comparison was always `false`. As far as I understand, the problem stems from the fact that `equal?` is defined as:

```
public defmulti equal? (a:Equalable, b:Equalable) -> True|False
```

Which means that the compiler has no way of noticing the mistake, because `Char` and `String` are both `Equalable`. However, we could introduce:

```
defn same-type-equal?<?T> (a:?T & Equalable, b:T & Equalable) -> True|False:
    a == b
```

Then compiling `same-type-equal?('y', "y")` gives the following error:

```
Cannot call function same-type-equal? of type (Equalable&Char, Equalable&Char) -> True|False 
with arguments of type (Char, String).
```

While `same-type-equal?('y', 'y')` compiles without error.

I see a few ways to solve this issue:
1. Create an `===` operator that would use same-type-equal? (And analogous `!==` operator), so that `'x' === "x"` does not compile. I like this option.
2. Add a method to the `equal?` multi for comparing `Char` values to `String` values.
3. Do nothing, developers should know to not write `'x' == "x"`.
4. Change `equal?` to `same-type-equal?`. From what I can tell, this goes against the design philosophy of the language, because users would no longer be able to write methods for `equal?` that take two different types, even if it makes sense in some cases.

I am interested in hearing other people's opinions on this issue, whether they think it should be solved, and if so, the best way to do so.

**Comment by CuppoJava** [comment]
I have run into this bug before as well, but haven't come up with an acceptable solution yet. The `same-type-equal?` has another problem as well, which is:

Assuming that `Circle` is a type of `Shape`:

```
val c : Circle = ...
val s : Shape = ...
if c === s : 
   println("c is the same as s")
```

The above doesn't type-check.

**Comment by dwnusbaum** [comment]
Oh, good point. Are there type level functions available, so that something like the following would be possible? 

```
defn same-type-equal? (a:?T <: Equalable, b:?U <: Equalable):
    if subtype(T, U) or subtype(U, T): ; Or typeof(a), etc...
        a == b
    else:
        throw(Exception("Cannot compare types %_ and %_" % [typeof(a), typeof(b)]
```

If so, then could the above be implemented as a macro expansion that would throw an error when compiling?

**Comment by CuppoJava** [comment]
There are no type level functions as of yet. But we might add them later to help sophisticated macro writers. 

The above problem is really quite subtle. Supposing `a` has type `T` and `b` and type `U`, then even the condition:

```
T <: U and U <: T
```

is not quite what you want because then the following is disallowed:

```
val c : Circle | Square = ...
val s : Square | Triangle = ...
if c === s : 
   println("c is the same as s")
```

The condition you really want is:

```
T intersects U is not empty
```

which is a complicated type concept indeed.

**Comment by dwnusbaum** [comment]
Thanks for explaining! I am used to Haskell's type system, where union types and subtype polymorphism aren't directly expressible, so I didn't even consider those issues, even though they are obvious in hindsight.

Do you have anything in the works that would make it possible to catch these errors?

**Comment by CuppoJava** [comment]
Yeah. The subtyping paradigm is fundamentally more flexible than Haskell's type class theory. And that comes with both advantages and disadvantages, as we can see here.

We're working on adding _bounded quantifiers_ to help with some of this. But that will take a while.

**Comment by dwnusbaum** [comment]
Ok, bounded quantifiers will definitely help. Thanks for all the quick responses. I'm really enjoying Stanza so far, keep up the great work!
