### ISSUE TITLE
"Cannot cast value to type" using struct as Key in HashTable.

### ISSUE THREAD

**Issue by andreaTP** [StanzaOrg/lbstanza-old#35]
A stanza program such as:

```
defstruct Point :
   x: Double
   y: Double

val hm: HashTable<Point,Vector<Point>> = HashTable<Point,Vector<Point>>()

hm[Point(0.0, 0.0)] = Vector<Point>()
```

compiles properly, unfortunately at runtime it crashes:

```
FATAL ERROR: Cannot cast value to type.
   at core/collections.stanza:382.16
   at core/collections.stanza:286.16
   at test.stanza:7.0
```

B.T.W.
found implementing this:
https://github.com/andreaferretti/kmeans/pull/47

**Comment by CuppoJava** [comment]
Hi Andrea.

If you use that HashTable constructor (the no argument version) then the type `K` needs to be a subtype of both `Equalable` and `Hashable`, and you need to provide appropriate methods for `equal?` and `hash`. 

```
defstruct Point <: Hashable & Equalable :
   x: Double
   y: Double

defmethod equal? (a:Point, b:Point) :
   x(a) == x(b) and
   y(a) == y(b)

defmethod hash (a:Point) :
   13 * hash(x(a)) + hash(y(a))
```

It is bad that currently Stanza does not give you a compile-time error if `K` is the wrong type. We are working on adding _bounded quantifiers_ to Stanza to catch these errors in the future. But it will take us some time.

Hope this solves your problem.
  -Patrick

**Comment by andreaTP** [comment]
Hi Patrick,
yes this solves my issue!
I update my implementation.

**Comment by andreaTP** [comment]
wow using this gain me a huge speed up!
from about 9 secs to 3!

**Comment by CuppoJava** [comment]
Cool!
