### ISSUE TITLE
[FEATURE REQUEST] named optional arguments

### ISSUE THREAD

**Issue by ewtoombs** [StanzaOrg/lbstanza-old#44]
In my experience, allowing less-often used arguments of a function to have sane defaults using named optional arguments has been extremely useful to writing flexible yet easy-to-use APIs. (In my opinion, it is python's single greatest feature.) Is this possible in lbstanza? If not, would you please consider implementing it? Maybe something like

```
defn line (x:Double, slope:Double, intercept:Double = 0) -> Double :
    intercept + slope * x
```

Or whatever variation on that makes the lexing and parsing easiest. `intercept` would not need to be specified, so `line(4, 4)` would produce `16`. `line(4, 4, intercept = -3)` would produce `13`.

**Comment by CuppoJava** [comment]
Thanks for the feedback. Named and optional arguments are in-progress for the next major release of Stanza. We are looking forward to it too!

**Comment by ewtoombs** [comment]
@CuppoJava : YESSSSSSSSSSSS! Oh, that is good news! Thank you for your efforts so far!
