### ISSUE TITLE
support for gcc 7?

### ISSUE THREAD

**Issue by ewtoombs** [StanzaOrg/lbstanza-old#46]
How far off is support for gcc 7? What version of gcc is currently supported?

**Comment by CuppoJava** [comment]
Hi.

Thank you for narrowing the issue to gcc 7. We will look into fixing this error very shortly. Stanza uses essentially only gcc's assembler and doesn't depend on any advanced languages features of C, so we consider this a bug rather than a feature request.

  -Patrick
