### ISSUE TITLE
memory leak in stanza-0.11.28?

### ISSUE THREAD

**Issue by ewtoombs** [StanzaOrg/lbstanza-old#47]
When compiling the git version of stanza using scripts/make-compiler.sh, the linux binary version of stanza-0.11.28 available from the website allocates in excess of 3.5 GiB of memory, then crashes with "Cannot allocate memory" after it tries to allocate more. (I only have 4 GiB of RAM.) Seems like a memory leak.

**Comment by CuppoJava** [comment]
Okay. We've reproduced the behaviour that you're seeing. Thanks for reporting it!!

**Comment by ewtoombs** [comment]
I switched on -verbose, and I think I got a different error, having to do with the message printing. Here it is anyway.
[debug.txt](https://github.com/StanzaOrg/lbstanza/files/1358192/debug.txt)

**Comment by CuppoJava** [comment]
Fixed with compiler-max-heap-size option in .stanza file. To limit the compiler's maximum heap size add the following line to your .stanza file:
```
compiler-max-heap-size = 1073741824L
```
The above sets the maximum heap size of the Stanza compiler to 1GB.

**Comment by ewtoombs** [comment]
Nice! Thanks for fixing, Patrick! Now, I might finally be able to build the git version...

**Comment by CuppoJava** [comment]
Thanks for the bug report! Let me know what happens!
