### ISSUE TITLE
Huge repository size due to commited binaries

### ISSUE THREAD

**Issue by tilpner** [StanzaOrg/lbstanza-old#5]
I assume the file `stanza` is for bootstrapping purposes.
Unfortunately, there's not just one "stanza", but probably dozens included in the repo, because all the history is conserved.

Considering the executable is OSX-only, it's not even useful/sufficient/required for users of other operating systems, yet they have download it dozens of times.

I just cloned it, the repo takes up 461MB for me, which might be a serious problem for people with a worse internet connection.

Could these executables perhaps be extracted into their own repo, and then linked as a submodule, or hosted in some other way?

**Comment by tilpner** [comment]
Simply removing `fast-pkgs`, `pkgs` and `stanza` from the repository shrinks the size to 21MB, additionally removing the unused blobs `defns.dat` and `stanza3` from history reduces the download size to 2MB.

I realize rewriting history is quite annoying, as everyone will have to update their local clones, but I think you should consider it, given the immense benefit in storage and download size.

I forked to [tilpner/lbstanza](/tilpner/lbstanza), then ran the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/).

**Comment by CuppoJava** [comment]
Thanks for the comments tilpner. We have to figure out a good way of doing this. 

Bootstrapping is a very fragile process, and each of the released sources are meant to be compiled with the compiler in that release. So the tracking between the binaries and the source is very important. We'll have to figure out how to keep this tracking correct, whilst also keeping the repo size down.

**Comment by tkelman** [comment]
I'd recommend attaching binary artifacts via github releases or an external hosting location like bintray. As long as the files are versioned (and probably named by architecture/platform too) and you don't touch them after uploading them, you can reference a static url in a bootstrap script.

**Comment by tilpner** [comment]
@CuppoJava Absolutely, full bootstrapping must still be possible, and ideally easy.

For a full bootstrap from the first commit, no binaries should be required. I don't know what the original compiler/interpreter was implemented in, but the bootstrapper would only have to install that one.

For a partial bootstrap, to only compile the latest version, binaries probably can't be avoided. The Rust project solved this by [downloading a recent build](http://static.rust-lang.org/dist/index.html) in order to compile the next compiler. This could neatly solve the distribution problem, but might require infrastructure that is not yet in place.

I am clueless as to how the bootstrapping can be synchronized with the git history.

**Comment by sumit0190** [comment]
I quite like the solution proposed by @tkelman; seems like the simplest solution.

**Comment by CuppoJava** [comment]
tkelman's solution sounds good to us as well. We'll refactor the repo in that direction.
