### ISSUE TITLE
No way to ask questions / have general discussion with devs

### ISSUE THREAD

**Issue by Sh4rK** [StanzaOrg/lbstanza-old#7]
Hi,

I find Stanza an interesting language, and would like to know more. Currently all I can do is read the docs, but if I have a question, I have nowhere to go. It would be awesome to have a mailing list and/or IRC channel (or something else).

**Comment by CuppoJava** [comment]
Thanks for your interest. We are in the midst of setting up a group list. And then users will be able to discuss issues, and help each other. This is also how I learned to program myself and it's very important to us.

**Comment by CuppoJava** [comment]
A mailing list and IRC channel has been set up!

**Comment by Sh4rK** [comment]
Cool!

**Comment by ewtoombs** [comment]
. . . so I'm in freenode#lbstanza right now. It appears to be empty...

**Comment by CuppoJava** [comment]
Hi.

We have the IRC channel set up so that we have a standard place to have real-time discussions if necessary, but we don't yet have the bandwidth to monitor the channel. You can ask questions on the mailing list though, and we are quite prompt about replying.

  -Patrick
