### ISSUE TITLE
Custom operator overloading

### ISSUE THREAD

**Issue by haze** [StanzaOrg/lbstanza-old#8]
I know there are default operators you can overload, but why isn't there any support for custom operators like |> or $?

**Comment by CuppoJava** [comment]
Operators in Stanza are implemented through a macro-expansion phase. The default operators already have macros that expand into calls to the plus, minus, times, etc. functions.

Custom operators can be implemented by writing new macros. It is already possible, but the feature has not been documented yet, as we are cleaning up some rough ends.
