### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by MadcapJake** [StanzaOrg/lbstanza-old#9]
I've created an IRC channel #lbstanza on freenode if anyone is interested ([webchat](http://webchat.freenode.net/?channels=lbstanza&nick=)). Perhaps it could be mentioned in the readme or on the website?

**Comment by CuppoJava** [comment]
That was a great idea. Thanks Jake! Let's make #lbstanza on freenode the official channel then. I'll add an announcement to the website.
